### PR TITLE
Remove trailing spaces

### PR DESCRIPTION
**Pull request by aborzunov**

### CODE REVIEW

**Comment by eyalroz** [comment]
@aborzunov : Would you mind recreating this PR to be against the `development` branch? I introduce changes there before they go on `master`.

**Comment by eyalroz** [comment]
... oh, it's just a single space. I'll do this myself. Thanks for noticing.

**Comment by eyalroz** [comment]
So, I removed a bunch of trailing spaces from several files at the tip of the development branch. See:
commit 4815d5bfe0111039d118961f74b856d980a30c90.

**Comment by aborzunov** [comment]
Yeah, great.
Only after creating PR i realised, that i should have checked all files, not the only one i was interested.
Thx!

**Comment by eyalroz** [comment]
By the way - if you happen to use the wrappers in an interesting project, do drop me a line so I could have a look (for some sense of pride... and for seeing whether there's something I could improve about them).

**Pull request closed without merging**
